version: "3.8"
services:
  shopper_db:
    image: postgres:13-alpine
    container_name: shopper_db
    ports:
      - 5433:5432
    restart: "no"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=shopper
    volumes:
      - ./resources/postgresql:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: "no"
    ports:
      - 7082:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tmp:/tmp